name: ny_cricket_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
    
  # State Management
  get: ^4.6.6
  
  # API
  dio: ^5.7.0
  
  # Data Models
  freezed: ^2.5.7
  json_annotation: ^4.9.0
    
  # Utils
  intl: ^0.19.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.14
  flutter_cache_manager: ^3.4.1
  lottie: ^3.1.3
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  smooth_page_indicator: ^1.2.0+3
  toastification: ^2.3.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  flutter_spinkit: ^5.2.1
  get_it: ^8.0.1
  injectable: ^2.5.0
  flutter_native_splash: ^2.4.2
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  shared_preferences: ^2.5.2
  flutter_easyloading: ^3.0.5
  cron: ^0.6.1
  google_mobile_ads: ^5.3.1
  image_picker: ^1.1.2
  permission_handler: ^11.4.0
  audioplayers: ^6.4.0
  
  

dev_dependencies:
   # Code Generation
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.4
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  intl_utils: ^2.8.7
  injectable_generator: ^2.6.2
  flutter_gen_runner: ^5.9.0

flutter_intl:
  enabled: true
  class_name: Lang
  main_locale: en
  arb_dir: lib/app/l10n 
  output_dir: lib/app/generated 

flutter_gen:
  output: lib/app/generated
  line_length: 80   
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true

flutter:
  uses-material-design: true
  assets: 
    - assets/images/pngs/
    - assets/images/pngs/authentication/
    - assets/images/pngs/onboarding/
    - assets/images/pngs/home/
    - assets/images/icons/
    - assets/images/jpgs/

flutter_native_splash:
  color: "#42a5f5"
  android_12: